version: "3.7"

services:
  url-shortening-service:
    build: .
    ports:
    - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - /var/redis:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes